version: "3.3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    command: redis-server --requirepass Wy108W@T86Kt
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "sample"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "5bAEsCVl882WBPA"
      MYSQL_ROOT_PASSWORD: "5bAEsCVl882WBPA"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
