version: "3.3"
services:
  redis_integration_test:
    image: "redis:alpine"
    ports:
      - 6388:6388
    command: redis-server --requirepass 832paNEy2YVMV9UK9s --port 6388
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "integration_test_db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "integration_test_user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "BpWBtamxs45CFLaCxo"
      MYSQL_ROOT_PASSWORD: "BpWBtamxs45CFLaCxo"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3309:3306"
